version: '3.1'
services:
  mongo-server:
    image: mongo
    ports:
      - "27018:27017"
    container_name: mongodb
    volumes:
      - ./db/:/data/db
  node-app:
    build:
      context: . 
      dockerfile: Dockerfile
    image: social-media-simulator
    ports:
      - "3000:3000"
    links:
      - mongo-server
    depends_on:
      - mongo-server
  
